N_THREADS = 6
N_CTX = 6 * 1024 #Total context window given to the model
MAX_TOKENS = 3 * 1024 #Cap on how many tokens the model is allowed to generate per call, used in other scripts
RESERVE_TOKENS = MAX_TOKENS + 16 #Used in the process_file script
N_CTX_MIN = 1024 #Floor in dynamic token allocation
N_CTX_MAX = 12 * 1024 #Upper limit on dynamic token allocation
SAFETY_MARGIN = 16
PRINT_PROCESSING_PROMPT = False
HIDE_THINKING_MODELS = True

SYSTEM_INSTRUCTION = " [Style: Omit formatting.]"
BASE = 'Role: You are a sequential text processing tool that is run from a script. Output only the requested text itself. Do not add any other explanations or comments. Provide the requested content directly without any introductory phrases. Write linear sentences without em dashes.'
TASK_LINE = "Instruction; carry out the following task"
REQUESTS = [
    'Write this segment into a slightly less difficult language, while preserving exactly the same meaning, nuance, tone, implications, qualifications, and level of detail. Leave sentences unchanged unless they contain wording that is unusually complex, formal, or cumbersome for an adult general reader. Replace heavily burdened vocabulary or excessively difficult words when more common alternatives would express the same meaning, but do this conservatively. Split up sentences that are overloaded with multiple distinct ideas. Do not summarize or remove information. Do not make the writing simpler than necessary; the goal is only to smooth excessive complexity. When a choice is uncertain, preserve the original wording. Do not use em dashes or snaily parenthetical insertions.',
    'Condense this book segment into a simple and clear encapsulation. Present the central causal mechanism while omitting less important details. It should be a compressed summary of the main point. Infer the underlying meaning instead of restating what the text said. Write for a reader that gets an entire book of similar segments summarized and wants to extract the gist from each segment, not have it repeated what is common about them. Assume the context is known and does not have to be repeated. Do not sanitize contrarian aspects. Apply the same narrative voice as the original content, without introductory phrases like “the takeaway is”.',
    'State this segment in different words, so that it means the same conceptually but is not immediately recognizable as the same text. The purpose is to not have it detected as being the same origin by algorithmic tools. You can compress the specifics a bit instead of being true to every detail. Try to change the order as well. Good presentation is not that important.',
    'Rewrite this passage so that it conveys the same meaning, but is phrased more like a formal nonfiction book. The tone should be less flippant and avoid sounding like a grievance, while expressing the same meaning. If the text is already good enough, then it can stay the same. Return the full adapted input passage without adding other changes or comments.',
    'Rewrite this text so that all sentences with em dashes are replaced with linear writing, either using commas or separate sentenes, so the text sounds natural and stops having snaily parenthetical insertions.',
    'Write down the conceptual lesson of this segment, as you experience it, stripped of the particular historic or practical situation it is demonstrated with. Compress this into one central causal functional lesson, rather than presenting several angles or fully representing all aspects. Describe this lesson directly without introductory phrases. Present it in the tone that the original author would have expressed it in, without hedging or sanitizing it. Assume the passage is part of a longer book of similar content, and that odd terminology makes sense in this context. Gramatically compress conceptually similar clauses into single statements.',
    'Respond with three suggestions for a title for this segment. Try to capture what is special about this content specifically. The title should be short; two to three words. It does not have to be exhaustively explanatory of the segments entire content, but should just be an identifier. The title does not have to mention all aspcets of the segment, but rather focus on an important one. Try to capture the core conceptual lesson or unique historical moment being presented. The title should be short and punchy, and provide a single-directional headline, containing a pun, inversion, or ironic reference that illustrates the central lesson of the content. Provide three distinct suggestions with no further comments.',
    'The task is to come up with a two-word title for this segment from a history book. Respond only with these two words.',
    'Write this compilation of summaries of paragraphs from a book into a coherent continuous-style nonfiction book segment that contains the explanation that the summaries seem to present. Round out the explanation where that improves understanding. Don\'t just repeat the same statements, but inferwhat they were expressing into a new presentation.',
    'Write a brief, compact list of central claims made in this segment in the format of short statements like “this does this”. It is not the aim to paraphrase the entire segment, but to express the core claims.',
    'Describe what single image should accompany this sentence in a video narration, given the surrounding context. The image must depict exactly one historical moment, as if it were a single historical photograph, not a montage, not a split screen, not multiple juxtaposed scenes, even if the sentence itself touches on several ideas or themes. The image does not need to capture every aspect of the content, but only needs to serve as one plausible background visual for that moment in the narration. If the sentence spans multiple ideas, pick the single most visually concrete moment to represent it and describe only that. Do not combine disjointed content that would not realistically have been captured in the same photograph. Exclusively describe one historical moment as it could have existed at one point in time. Choose simple, visually easy to understand scenes, that are still distinct enough to represent the particular era or concept in question. Output a description of the scene so that it can be used in a image generator prompt with no further comment. Do not mention the art style, image type, or camera framing; only describe the content itself. Briefly mention the desired emotional effect of the image, so that the image generator gets an indication what intention to carry out.',
    'Summarize this book segment into a simple and clear encapsulation, of at most one to three sentences. Present the central causal mechanism rather than to focus on details. Write for a reader that has all segments from the book this segment is in summarized and wants a short version of each one. Formulate this in a compressed language instead of restating what the text already says. Focus on what unique contrarian claims are present in this segment. Apply the same narrative voice as the original, without introductory phrases that mention the segment.',
    'Sum up in at most four words what this segment is conceptually about. Capture the core conceptual lesson or unique historical moment being presented. This is meant to be a small subchapter title for the segment. Only respond those four words or less.',
    'This segment is an attempt to express certain ideas, but it was written in a somewhat cumbersome way. Can you rewrite what it appears to convey into better prose, while making the output true to the intention and nuance of the input. This means not sanitizing the content into a more socially appropriate variant. Do largely apply the terms that the original used, while fixing sentence structure, order, and amount of sentences. Where helpful for comprehension, add explanatory content rather than shortening the explanation.',
    'Express the central causal mechanism of this history book segment in one sentence.',
    'Write an analysis of what you think this history segment represents as a emotional-symbolic psychologism for the writer. Try to infer and describe the emotional state of the writer.',
]
SUMMARY_INSTRUCTION = "Now generate the context from this conversation for the next prompt. Write key facts from the exchange between a user and assistant as compressed context. Good grammar is not needed. Write this as one continuous unformatted text without segmentation. Don't analyze or comment. The purpose is to provicde a truncation of the previous conversation that includes its factual data. Keep mor edetail from the later parts and truncate the earlier parts of the conversation more. Keep most of what the user said while truncating assistant answers more. Grow the length of the summary in line with the content.\n\n"
CODE_TASK = "Instruction: This is a generated description about a function from the source code from the video game Rome Total War. Suggest a flatcase name appendage for the function to distinguish it from others, that mainly highlights what part of the code it belongs to, not so much its specific functionality (which might be interpreted wrongly by the LLM). Output just this name in one combined string."

