N_THREADS = 6
N_CTX = 6 * 1024 #Total context window given to the model
MAX_TOKENS = 3 * 1024 #Cap on how many tokens the model is allowed to generate per call, used in other scripts
RESERVE_TOKENS = MAX_TOKENS + 16 #Used in the process_file script
N_CTX_MIN = 1024 #Floor in dynamic token allocation
N_CTX_MAX = 12 * 1024 #Upper limit on dynamic token allocation
PRINT_PROCESSING_PROMPT = False
SYSTEM_INSTRUCTION = ""
BASE = 'Role: You are a sequential text processing tool that is run from a script. Output only the requested text itself. Do not add any other explanations or comments.'
REQUESTS = [
    'Condense this book segment into a simple and clear encapsulation. Present the central causal mechanism while omitting less important details. It should be a compressed summary of the main point. Infer the underlying meaning instead of restating what the text said. Write for a reader that gets an entire book of similar segments summarized and wants to extract the gist from each segment, not have it repeated what is common about them. Assume the context is known and does not have to be repeated. Do not sanitize contrarian aspects. Apply the same narrative voice as the original content without introductory phrases like “the takeaway is”.',
    'Write this segment into a slightly less difficult language, while preserving exactly the same meaning, nuance, tone, implications, qualifications, and level of detail. Leave sentences unchanged unless they contain wording that is unusually complex, formal, or cumbersome for an adult general reader. Replace heavily burdened vocabulary or excessively difficult words when more common alternatives would express the same meaning, but do this conservatively. Try to stay accurate to the originals nuance. Split sentences that are overloaded with multiple distinct ideas. But do not summarize or remove information. Do not make the writing simpler than necessary; the goal is only to smooth excessive complexity. When a choice is uncertain, preserve the original wording. Never use em dashes or snaily parenthetical insertions.',
    'Comment on the ideas in this segment from a book. The point is not to repeat or summarize the content, but to comment on it.',
    'Write this segment into different words, so it means the same but is not immediately recognizable as the same text. The purpose is to be able to paste the text into online tools without having it detected as being the same.',
    'Suggest a descriptive name to append to the name of the C code function that was summarized by this text block. The main concern is a categorization into game systems within the Rome Total War executable. Uninteresting housekeeping subroutines shuld simply be named as such. In the name distinguish interesting functions that might have uses a modder might be interested in from ones that are uninteresting housekeeping, engine setup, or memory management. The name can be several words in flatcase.',
    'This is a decompilers C-style reconstruction of a function from the executable of the video game Rome Total War. Describe this functions apparent purpose and role within the games systems. State only what is directly supported by code and data structures, but include high confidence inferences where appropriate. The description should attempt to be on the level of broader holistic purposerather than particular implementation detail. Return the response as a JSON object with exactly these fields: \"name\": a suggestion for a descriptive flatcase name to append to the generated function name. \"purpose\": a documentation annotation describing the functions apparent conceptual responsibility, the game concepts it operates on, what role it most likely serves within the games logic, and any high confidence inferences that would help distinguish it from other functions in the game. Prefer including useful context over brevity. Do not describe implementation details unless they are necessary to explain the conceptual role. Focus on what matters to the player, not the algorithmic details. \"domain\": the primary game system or engine domain this function belongs to. This should be a categorization into subsystems by which functions can later be sorted. \"keywords\": a comprehensive list of search terms that someone reverse engineering the game might later search for, including game concepts, mechanics, entities, systems, and closely related concepts. Include plausible synonyms where supported by the code. Do not overly focus on implementation terminology. \"modding_relevant\": a boolean that is true only if this function appears to define, compute, or directly apply a game mechanic that a reverse engineer would likely modify to intentionally change gameplay. Return false for wrappers, accessors, dispatchers, lookups, validation, state management, scripting infrastructure, rendering, UI, or other supporting functions, even if they participate in gameplay. Modders care about application of in-game effects or healing casualties calculations, not assert plumbing. \"modding_explanation\": Explanation of the choice of the `modding` value. \"arguments\": As far as possible to infer from this stripped code, provide a segment on what data the function handles and what arguments it passes on to the functions it calls or what data they contain. This information is meant to later be included in the context when generating these functions annotations, so it can be known what data they received. This is difficult to say with stripped code, so state what is known at this time.\n Output a JSON object with no surrounding text, code fences, backticks, or headers.',
    'This is a segment from a book of similar content. Respond with the title this segment should have, meant as a brief header. This is processed sequentially so that each part of the book gets a title instead of just a number. Try to capture what is likely special about this segment. This should be short; three words if possible, but go by what would be optimal for this passage. It does not have to be fully explanatory, it is just a identifier; and does not have to mention all aspcets of the segment, just one important one. Do not have any \"and\" in this, it should be a single-pointed punchy headline.',
    'Give three short pieces of advice on how this segment of a book could be improved. Do you see obvious factual mistakes, repetition, or does the writing that sound like a grievance? Return these as brief notes in list format. If there isn\'t much then don\'t write much. It can be assumed that terms and context are established in earlier segments.',
    'Write this passage so that it is phrased like a serious history book, but conveys the same meaning. It should not sound like a grievance. Try to keep the meaning the same. Much of the text can stay the same. Return the full passage without other changes while fixing obvious spelling mistakes (which are unlikely).',
    'Make a list of what suggestions for corrections you find in this segment. This means primarily spelling or serious gramattical errors. But also factual mistakes if they are objective, ways the content could be written better, or parts that seem off.',
    'Rewrite this text so that all sentences with em dashes are replaced with linear writing, either using commas or separate sentenes, so the text sounds natural.',
    'Write down the conceptual lesson of this passage, as you experience its meaning from this segment, stripped of the particular historic or practical situation it is demonstrated with. Compress this into one central causal functionalist lesson rather than presenting an exhaustive treatment of the full content. Describe this lesson directly without introductory phrases. State it like the original author would have said it, without hedging or sanitizing. Assume the passage is part of a longer book of similar content and the surrounding context is known, and that odd terminology makes sense in context. Gramatically compress conceptually similar clauses into one statement.',
    'Respond with the title this paragraph from a book should have as a brief header within the book. This is part of sequentially processing the entire book, so that each segment gets a title. Try to capture what is likely special about this segment, i.e. assume that the surrounding segments will have similar content. This title should be short; two to three words, if possible, but the length should depend on what would be optimal for this particular passage. The title does not have to be exhaustively explanatory, but just be a relevant identifier. It does not have to mention all aspcets of the segment, just an important one. It should be a single-directional punchy headline. The title should be more about the placement of the content in informational categorization than what is happening. It could even have a slight pun or inversion in it that highlights the point. It should just be a short, punchy segment title. Keep in mind that the content nearby is on the same historic subject, so it should not just be that, so that the title differentiates between them.',
    'Write this compilation of summaries of paragraphs from a book into a coherent continuous-style history book segment that contains the explanation that the summaries seem to present. Round out the explanation where that improves understanding. Don\'t just repeat the same statements, but inferwhat they were expressing into a new presentation.',
    'Write a brief, compact list of central claims made in this segment in the format of short statements like "this does this".',
    'Write these separate prompts into one comprehensive article that explains what they are trying to exlpain. Round out this explanation Include all details.',
    'Describe what single image should accompany this sentence in a video narration, given the surrounding context. The image must depict exactly one historical moment, as if it were a single historical photograph, not a montage, not a split screen, not multiple juxtaposed scenes, and no disjointed content in the background that would not realistically be in the same photograph, even if the sentence itself touches on several ideas or themes. The image does not need to capture everything the sentence says, it only needs to serve as one plausible background visual for that moment in the narration. If the sentence spans multiple ideas, pick the single most visually concrete moment from it and describe only that. Do not show industrial facilities with agricultiral workers, do not show a British port facility with Dutch canals or other disjointed content that would not realistically have been captured in the same photograph; exclusively describe ONE HISTORICAL MOMENT as it could have existed. Do not juxtapose the different aspects shown in the text, just show one of them. Try to come up with simple, easy to understand scenes, that are still specific enough to highlight the particular era in question rather than generic content. The image should feel like a natural continuation of the previous image, not a jarring new direction. Exclusively output an image description that will be used in a image generator, with no further comment. Sparingly include camera framing if it would be relevant for the image generation. Do not mention what style the image should have, only describe the content itself. Also include the intention of the image that isn\'t directly visual, so that the generator has an anchor of what desired intended emotional effect to aim for.',
    'Fix the grammar and spelling of this text passage, but otherwise write it exactly as what it it trying to convey. You may split sentences that are long, but do not summarize or remove information.',
    'Summarize this text segment into a simple and clear encapsulation. Present the central mechanism and infer the underlying meaning instead of restating what the text said. Write for a reader that gets several similar segments summarized. Infer interpretatively. Do not sanitize the content. Apply the same narrative voice as the original.',
]
SUMMARY_INSTRUCTION = "Now generate the context from this conversation for the next prompt. Write key facts from the exchange between a user and assistant as compressed context. Good grammar is not needed. Write this as one continuous unformatted text without segmentation. Don't analyze or comment. The purpose is to provicde a truncation of the previous conversation that includes its factual data. Keep mor edetail from the later parts and truncate the earlier parts of the conversation more. Keep most of what the user said while truncating assistant answers more. Grow the length of the summary in line with the content.\n\n"
CODE_TASK = "Instruction: This is a generated description about a function from the source code from the video game Rome Total War. Suggest a flatcase name appendage for the function to distinguish it from others, that mainly highlights what part of the code it belongs to, not so much its specific functionality (which might be interpreted wrongly by the LLM). Output just this name in one combined string."

