N_THREADS = 6
N_CTX = 6 * 1024 #Total context window given to the model
MAX_TOKENS = 3 * 1024 #Cap on how many tokens the model is allowed to generate per call, used in other scripts
RESERVE_TOKENS = MAX_TOKENS + 16 #Used in the process_file script
N_CTX_MIN = 1024 #Floor in dynamic token allocation
N_CTX_MAX = 12 * 1024 #Upper limit on dynamic token allocation
PRINT_PROCESSING_PROMPT = False
SYSTEM_INSTRUCTION = " [Style: Omit formatting.]"
BASE = 'Role: You are a sequential text processing tool that is run from a script. Output only the requested text itself. Do not add any other explanations or comments. Provide the requested content directly without any introductory phrases. Write linear sentences without em dashes.'
REQUESTS = [
    'Write this segment into a slightly less difficult language, while preserving exactly the same meaning, nuance, tone, implications, qualifications, and level of detail. Leave sentences unchanged unless they contain wording that is unusually complex, formal, or cumbersome for an adult general reader. Replace heavily burdened vocabulary or excessively difficult words when more common alternatives would express the same meaning, but do this conservatively. Split up sentences that are overloaded with multiple distinct ideas. Do not summarize or remove information. Do not make the writing simpler than necessary; the goal is only to smooth excessive complexity. When a choice is uncertain, preserve the original wording. Do not use em dashes or snaily parenthetical insertions.',
    'Condense this book segment into a simple and clear encapsulation. Present the central causal mechanism while omitting less important details. It should be a compressed summary of the main point. Infer the underlying meaning instead of restating what the text said. Write for a reader that gets an entire book of similar segments summarized and wants to extract the gist from each segment, not have it repeated what is common about them. Assume the context is known and does not have to be repeated. Do not sanitize contrarian aspects. Apply the same narrative voice as the original content without introductory phrases like “the takeaway is”.',
    'Comment on the ideas in this segment from a book. The point is not to repeat or summarize the ideas presented here, but to evaluate them freely.',
    'Respond with three short pieces of advice on how this segment of a book could be improved. Examples could be obvious factual mistakes, repetitive content, or writing that sounds too much like a grievance. Return these as brief notes in list format. If there isn\'t much wrong with the text then don\'t write much. It can be assumed that terms and context are established in earlier segments.',
    'Write this segment into different words, so that it means the same but is not immediately recognizable as the same text. The purpose is to not have it detected as being the same origin by algorithmic tools.',
    'Write this passage so that it is phrased like a serious nonfiction book, but conveys the same meaning. It should not sound like a grievance. Try to keep the meaning the same. Much of the text can stay the same. Return the full passage without other changes while fixing obvious spelling mistakes (which are unlikely).',
    'Make a list of what suggestions for corrections you find in this segment. This means primarily spelling or serious gramattical errors. But also factual mistakes if they are objective, ways the content could be written better, or parts that seem off.',
    'Rewrite this text so that all sentences with em dashes are replaced with linear writing, either using commas or separate sentenes, so the text sounds natural and stops having snaily parenthetical insertions.',
    'Write down the conceptual lesson of this passage, as you experience its meaning from this segment, stripped of the particular historic or practical situation it is demonstrated with. Compress this into one central causal functionalist lesson, rather than presenting an multi-point treatment of the full content. Describe this lesson directly without introductory phrases. Present it like the original author would have phrased it, without hedging or sanitizing towards social acceptability. Assume the passage is part of a longer book of similar content and the surrounding context is known, and that odd terminology makes sense in context. Gramatically compress conceptually similar clauses into single statements.',
    'Respond with three suggestions for a title this paragraph from a book could have. The title will be used as a unique header within the book. Try to capture what is special about this segment even when surrounding segments are about similar content. This title should be short; two to three words, if possible, but the length is flexible and can depend on what would be optimal for this particular passage. The title does not have to be exhaustively explanatory of the passages entire content, but should just be a relevant identifier. It does not have to mention all aspcets of the segment, so focus on an important one. Try to capture the core conceptual lesson or unique historical moment being presented. The title should be a single-directional punchy headline, for instance a slight pun, inversion, or reference. This should be short and punchy. Keep in mind that the content nearby is on the same historic subject, so this title has to distinguish itself from it. Provide three distinct suggestions with no further comment.',
    'What title could the chapter from a book that this paragraph is in have? Try to express what the broader these mseems to be. This title should be short, about two to three words. The title does not have to be exhaustively explanatory, but just be a relevant identifier. It does not have to mention all aspcets, just an important one. It should be a single-directional punchy headline. The title should be more about the placement of the content in informational categorization. It could even have a slight pun, inversion, or reference that highlights the point. It should just be a short, punchy title. Provide three suggestions.',
    'Write this compilation of summaries of paragraphs from a book into a coherent continuous-style nonfiction book segment that contains the explanation that the summaries seem to present. Round out the explanation where that improves understanding. Don\'t just repeat the same statements, but inferwhat they were expressing into a new presentation.',
    'Write a brief, compact list of central claims made in this segment in the format of short statements like "this does this". It is not the point to paraphrase the entire segment, but to find the core claims.',
    'Write these separate prompts into one comprehensive article that explains what they are trying to exlpain. Round out this explanation Include all details.',
    'Describe what single image should accompany this sentence in a video narration, given the surrounding context. The image must depict exactly one historical moment, as if it were a single historical photograph, not a montage, not a split screen, not multiple juxtaposed scenes, and no disjointed content in the background that would not realistically be in the same photograph, even if the sentence itself touches on several ideas or themes. The image does not need to capture everything the sentence says, it only needs to serve as one plausible background visual for that moment in the narration. If the sentence spans multiple ideas, pick the single most visually concrete moment from it and describe only that. Do not show industrial facilities with agricultiral workers, do not show a British port facility with Dutch canals or other disjointed content that would not realistically have been captured in the same photograph; exclusively describe ONE HISTORICAL MOMENT as it could have existed. Do not juxtapose the different aspects shown in the text, just show one of them. Try to come up with simple, easy to understand scenes, that are still specific enough to highlight the particular era in question rather than generic content. The image should feel like a natural continuation of the previous image, not a jarring new direction. Exclusively output an image description that will be used in a image generator, with no further comment. Sparingly include camera framing if it would be relevant for the image generation. Do not mention anything about the art style or image type, only describe the content itself. Also include the intention of the image that isn\'t directly visual, so that the generator has an anchor of what desired intended emotional effect to aim for.',
    'Summarize this text segment into a simple and clear encapsulation. Present the central mechanism and infer the underlying meaning instead of restating what the text said. Write for a reader that gets several similar segments summarized. Infer interpretatively. Do not sanitize the content. Apply the same narrative voice as the original.',
    'Make many suggestions for sentences or parts of sentences in this text segment that could be quoted as a short, punchy tagline for the book it is in. Limit your output to a few good ones that make sense when heard in isolation, yet give a taste for the content.',
    'Suggest several two to four word titles that a chapter containing this segment could be identified by. Infer what the broader chapter would be about. The title suggestiosn should contain a sarcastic reference or witty inversion.',
    'Sum up in at most four words what this segment is conceptually about. Capture the core conceptual lesson or unique historical moment being presented. This is meant to be a small subchapter title for the segment. Only respond those four words or less.',
    'Write in one word what this segment is about. Capture the core conceptual lesson or unique historical moment being presented. This is meant to be a small subchapter title for the segment, so it may contain sarcasm or irony if that brings the point across. Only respond exactly that one (or at the very most two) words. Try to be a bit imaginative, so that segments have distinct titles.',
    'Respond with a brief comment on this book segment.',
    'Briefly summarize what this segment appears to be about. Present this without introductory phrases; do not mention the passage or the author, simply state it in the same narrative voice.',
    'This segment is an attempt to express certain ideas, but it was written in a somewhat cumbersome way. Can you rewrite what it appears to convey into better prose, while making the output true to the intention and nuance of the input. This means not sanitizing the content into a more socially appropriate variant. Do largely apply the terms that the original used, while fixing sentence structure, order, and amount of sentences. Where helpful for comprehension, add explanatory content rather than shortening the explanation.',
]
SUMMARY_INSTRUCTION = "Now generate the context from this conversation for the next prompt. Write key facts from the exchange between a user and assistant as compressed context. Good grammar is not needed. Write this as one continuous unformatted text without segmentation. Don't analyze or comment. The purpose is to provicde a truncation of the previous conversation that includes its factual data. Keep mor edetail from the later parts and truncate the earlier parts of the conversation more. Keep most of what the user said while truncating assistant answers more. Grow the length of the summary in line with the content.\n\n"
CODE_TASK = "Instruction: This is a generated description about a function from the source code from the video game Rome Total War. Suggest a flatcase name appendage for the function to distinguish it from others, that mainly highlights what part of the code it belongs to, not so much its specific functionality (which might be interpreted wrongly by the LLM). Output just this name in one combined string."

